### ISSUE TITLE
Bad version of OpenLiveWriter on Chocolatey

### ISSUE THREAD

**Issue by nycdotnet** [csi-windowschocolatey/openlivewriter#1]
Hi @DarwinJS ,

I found this repository via the "Possible Package Source" link here: https://chocolatey.org/packages/openlivewriter

The version of Open Live Writer on Chocolatey is not the correct one - it is lacking some secrets that are included at compile time so it can work with Google Blogger.  The version on the openlivewriter.org site is correct.

The .nuspec file here doesn't match the package on Chocolatey either - it looks like the .nuspec here and the install PowerShell script will do the right thing and download Open Live Writer from the official web site.  Have you been in touch with the Chocolatey folks to get this package updated?

Thanks

**Comment by DarwinJS** [comment]
I did the initial package for this and now the openlivewriter team maintains it.  So this source is no longer the right stuff.  You can click the package maintainer name on chocolatey to contact them.

**Comment by nycdotnet** [comment]
Thanks
